// Search module
export const SEARCH_INPUT_UPDATE = 'SEARCH_INPUT_UPDATE'
export const SEARCH_INPUT_CLEAR = 'SEARCH_INPUT_CLEAR'

// Results model
export const RESULTS_QUERY = 'RESULTS_QUERY'
export const RESULTS_SUCCESS = 'RESULTS_SUCCESS'
export const RESULTS_FAILURE = 'RESULTS_FAILURE'
